//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NimbusACAD.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Negocio_Doc_Devente
    {
        public int Doc_Devente_ID { get; set; }
        public int Documento_ID { get; set; }
        public int Matricula_ID { get; set; }
    
        public virtual Negocio_Documento Negocio_Documento { get; set; }
        public virtual Negocio_Matricula_Aluno Negocio_Matricula_Aluno { get; set; }
    }
}
