//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NimbusACAD.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Negocio_Funcionario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Negocio_Funcionario()
        {
            this.Negocio_Curso = new HashSet<Negocio_Curso>();
            this.Negocio_Disciplina = new HashSet<Negocio_Disciplina>();
            this.Negocio_Frequencia = new HashSet<Negocio_Frequencia>();
        }
    
        public int Funcionario_ID { get; set; }
        public int Pessoa_ID { get; set; }
        public int Tipo_Funcionario_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Negocio_Curso> Negocio_Curso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Negocio_Disciplina> Negocio_Disciplina { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Negocio_Frequencia> Negocio_Frequencia { get; set; }
        public virtual Negocio_Pessoa Negocio_Pessoa { get; set; }
        public virtual Negocio_Tipo_Funcionario Negocio_Tipo_Funcionario { get; set; }
    }
}
