//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NimbusACAD.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Negocio_Frequencia
    {
        public int Frequencia_ID { get; set; }
        public int Disciplina_ID { get; set; }
        public int Funcionario_ID { get; set; }
        public Nullable<System.DateTime> Dt_Aula { get; set; }
        public Nullable<int> Qtde_Aula { get; set; }
        public string Aula_Ministrada { get; set; }
        public int Matricula_ID { get; set; }
    
        public virtual Negocio_Disciplina Negocio_Disciplina { get; set; }
        public virtual Negocio_Matricula_Aluno Negocio_Matricula_Aluno { get; set; }
        public virtual Negocio_Funcionario Negocio_Funcionario { get; set; }
    }
}
