//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NimbusACAD.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Negocio_Curso
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Negocio_Curso()
        {
            this.Negocio_Matricula_Aluno = new HashSet<Negocio_Matricula_Aluno>();
            this.Negocio_Modulo = new HashSet<Negocio_Modulo>();
        }
    
        public int Curso_ID { get; set; }
        public string Curso_Nome { get; set; }
        public string Descricao { get; set; }
        public string Periodo { get; set; }
        public int Funcionario_ID { get; set; }
        public Nullable<int> Carga_Horaria { get; set; }
    
        public virtual Negocio_Funcionario Negocio_Funcionario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Negocio_Matricula_Aluno> Negocio_Matricula_Aluno { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Negocio_Modulo> Negocio_Modulo { get; set; }
    }
}
