//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NimbusACAD.Models.DB
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Negocio_Notificacao
    {
        [Key]
        public int Notificacao_ID { get; set; }
        public int Pessoa_Emissor_ID { get; set; }
        public int Pessoa_Receptor_ID { get; set; }
        public string Assunto { get; set; }
        public string Corpo { get; set; }
        public Nullable<bool> Lida { get; set; }
    
        public virtual Negocio_Pessoa Negocio_Pessoa { get; set; }
        public virtual Negocio_Pessoa Negocio_Pessoa1 { get; set; }
    }
}
