//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NimbusACAD.Models.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NimbusAcad_DB_Entities : DbContext
    {
        public NimbusAcad_DB_Entities()
            : base("name=NimbusAcad_DB_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Negocio_Base_Endereco> Negocio_Base_Endereco { get; set; }
        public virtual DbSet<Negocio_Curriculo> Negocio_Curriculo { get; set; }
        public virtual DbSet<Negocio_Curso> Negocio_Curso { get; set; }
        public virtual DbSet<Negocio_Disciplina> Negocio_Disciplina { get; set; }
        public virtual DbSet<Negocio_Doc_Devente> Negocio_Doc_Devente { get; set; }
        public virtual DbSet<Negocio_Documento> Negocio_Documento { get; set; }
        public virtual DbSet<Negocio_Endereco> Negocio_Endereco { get; set; }
        public virtual DbSet<Negocio_Frequencia> Negocio_Frequencia { get; set; }
        public virtual DbSet<Negocio_Funcionario> Negocio_Funcionario { get; set; }
        public virtual DbSet<Negocio_Matricula_Aluno> Negocio_Matricula_Aluno { get; set; }
        public virtual DbSet<Negocio_Modulo> Negocio_Modulo { get; set; }
        public virtual DbSet<Negocio_Notificacao> Negocio_Notificacao { get; set; }
        public virtual DbSet<Negocio_Pessoa> Negocio_Pessoa { get; set; }
        public virtual DbSet<Negocio_Quadro_Horario> Negocio_Quadro_Horario { get; set; }
        public virtual DbSet<Negocio_Tipo_Funcionario> Negocio_Tipo_Funcionario { get; set; }
        public virtual DbSet<Negocio_Vinculo_Disciplina> Negocio_Vinculo_Disciplina { get; set; }
        public virtual DbSet<Negocio_Vinculo_Modulo> Negocio_Vinculo_Modulo { get; set; }
        public virtual DbSet<RBAC_Link_Perfil_Permissao> RBAC_Link_Perfil_Permissao { get; set; }
        public virtual DbSet<RBAC_Link_Usuario_Perfil> RBAC_Link_Usuario_Perfil { get; set; }
        public virtual DbSet<RBAC_Perfil> RBAC_Perfil { get; set; }
        public virtual DbSet<RBAC_Permissao> RBAC_Permissao { get; set; }
        public virtual DbSet<RBAC_Usuario> RBAC_Usuario { get; set; }
    }
}
