//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NimbusACAD.Models.DB
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class RBAC_Link_Perfil_Permissao
    {
        [Key]
        public int Link_ID { get; set; }
        public int Perfil_ID { get; set; }
        public int Permissao_ID { get; set; }
    
        public virtual RBAC_Perfil RBAC_Perfil { get; set; }
        public virtual RBAC_Permissao RBAC_Permissao { get; set; }
    }
}
