//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NimbusACAD.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class RBAC_Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RBAC_Usuario()
        {
            this.RBAC_Link_Usuario_Perfil = new HashSet<RBAC_Link_Usuario_Perfil>();
        }
    
        public int Usuario_ID { get; set; }
        public Nullable<int> Pessoa_ID { get; set; }
        public string Username { get; set; }
        public string Senha_Hash { get; set; }
        public string Salt { get; set; }
        public Nullable<System.DateTime> Dt_Criacao { get; set; }
        public Nullable<System.DateTime> Dt_Ultima_Modif { get; set; }
        public Nullable<bool> Bloqueado { get; set; }
    
        public virtual Negocio_Pessoa Negocio_Pessoa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RBAC_Link_Usuario_Perfil> RBAC_Link_Usuario_Perfil { get; set; }
    }
}
