//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NimbusACAD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Negocio_Pessoa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Negocio_Pessoa()
        {
            this.Negocio_Curriculo = new HashSet<Negocio_Curriculo>();
            this.Negocio_Endereco = new HashSet<Negocio_Endereco>();
            this.Negocio_Funcionario = new HashSet<Negocio_Funcionario>();
            this.Negocio_Matricula_Aluno = new HashSet<Negocio_Matricula_Aluno>();
            this.Negocio_Notificacao = new HashSet<Negocio_Notificacao>();
            this.Negocio_Notificacao1 = new HashSet<Negocio_Notificacao>();
            this.RBAC_Usuario = new HashSet<RBAC_Usuario>();
        }
    
        public int Pessoa_ID { get; set; }
        public string Primeiro_Nome { get; set; }
        public string Sobrenome { get; set; }
        public string CPF { get; set; }
        public string RG { get; set; }
        public string Sexo { get; set; }
        public Nullable<System.DateTime> Dt_Nascimento { get; set; }
        public string Tel_Principal { get; set; }
        public string Tel_Opcional { get; set; }
        public string Email { get; set; }
        public Nullable<bool> Email_Confirmado { get; set; }
        public Nullable<int> Tot_Notif_NL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Negocio_Curriculo> Negocio_Curriculo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Negocio_Endereco> Negocio_Endereco { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Negocio_Funcionario> Negocio_Funcionario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Negocio_Matricula_Aluno> Negocio_Matricula_Aluno { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Negocio_Notificacao> Negocio_Notificacao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Negocio_Notificacao> Negocio_Notificacao1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RBAC_Usuario> RBAC_Usuario { get; set; }
    }
}
