//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NimbusACAD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Negocio_Matricula_Aluno
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Negocio_Matricula_Aluno()
        {
            this.Negocio_Frequencia = new HashSet<Negocio_Frequencia>();
            this.Negocio_Vinculo_Disciplina = new HashSet<Negocio_Vinculo_Disciplina>();
            this.Negocio_Vinculo_Modulo = new HashSet<Negocio_Vinculo_Modulo>();
            this.Negocio_Documento = new HashSet<Negocio_Documento>();
        }
    
        public int Matricula_ID { get; set; }
        public int Pessoa_ID { get; set; }
        public int Curso_ID { get; set; }
        public Nullable<int> Ano { get; set; }
        public Nullable<bool> Ativo { get; set; }
        public Nullable<bool> Deve_Documento { get; set; }
    
        public virtual Negocio_Curso Negocio_Curso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Negocio_Frequencia> Negocio_Frequencia { get; set; }
        public virtual Negocio_Pessoa Negocio_Pessoa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Negocio_Vinculo_Disciplina> Negocio_Vinculo_Disciplina { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Negocio_Vinculo_Modulo> Negocio_Vinculo_Modulo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Negocio_Documento> Negocio_Documento { get; set; }
    }
}
