//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NimbusACAD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Negocio_Vinculo_Disciplina
    {
        public int Disciplina_ID { get; set; }
        public int Matricula_ID { get; set; }
        public Nullable<double> Nota1 { get; set; }
        public Nullable<double> Nota2 { get; set; }
        public Nullable<double> Media_Final { get; set; }
        public Nullable<int> Frequencia { get; set; }
        public Nullable<int> Num_Chamada { get; set; }
    
        public virtual Negocio_Disciplina Negocio_Disciplina { get; set; }
        public virtual Negocio_Matricula_Aluno Negocio_Matricula_Aluno { get; set; }
    }
}
