//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NimbusACAD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Negocio_Endereco
    {
        public int Endereco_ID { get; set; }
        public string CEP { get; set; }
        public string Complemento { get; set; }
        public Nullable<int> Numero { get; set; }
        public Nullable<bool> Ativo { get; set; }
        public int Pessoa_ID { get; set; }
    
        public virtual Negocio_Base_Endereco Negocio_Base_Endereco { get; set; }
        public virtual Negocio_Pessoa Negocio_Pessoa { get; set; }
    }
}
