//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NimbusACAD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Negocio_Vinculo_Modulo
    {
        public int Modulo_ID { get; set; }
        public int Matricula_ID { get; set; }
        public string Status_Vinculo { get; set; }
    
        public virtual Negocio_Matricula_Aluno Negocio_Matricula_Aluno { get; set; }
        public virtual Negocio_Modulo Negocio_Modulo { get; set; }
    }
}
